[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag    = "noindex, nofollow"
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
